In [34]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import copy

In [7]:
#将训练集中的log和truth进行合并
df1 = pd.read_csv('./row_data/train_log.csv')
df2 = pd.read_csv('./row_data/train_truth.csv')
left = pd.merge(df1,df2,on=['enroll_id'],how='left')
left

,enroll_id,username,course_id,session_id,action,object,time,truth
0,772,5981,course-v1:TsinghuaX+70800232X+2015_T2,d8a9b787fa69063c34c73b9c29190b1c,click_about,NaN,2015-09-27T15:42:59,1
1,772,5981,course-v1:TsinghuaX+70800232X+2015_T2,d8a9b787fa69063c34c73b9c29190b1c,click_info,NaN,2015-09-27T15:43:12,1
2,773,1544995,course-v1:TsinghuaX+70800232X+2015_T2,2f02b86eb3ea2cbf0be11385a8dc62e5,pause_video,3dac5590435e43b3a65a9ae7426c16db,2015-10-19T19:37:42,1
3,773,1544995,course-v1:TsinghuaX+70800232X+2015_T2,2f02b86eb3ea2cbf0be11385a8dc62e5,load_video,3dac5590435e43b3a65a9ae7426c16db,2015-10-19T19:33:27,1
4,773,1544995,course-v1:TsinghuaX+70800232X+2015_T2,2f02b86eb3ea2cbf0be11385a8dc62e5,play_video,3dac5590435e43b3a65a9ae7426c16db,2015-10-19T19:33:30,1
...,...,...,...,...,...,...,...,...
29165535,466786,2659552,course-v1:TsinghuaX+AP000001X+2016_T1,dff9476c7f05f26a69a06506fe471668,click_courseware,NaN,2016-04-01T21:04:38,0
29165536,466786,2659552,course-v1:TsinghuaX+AP000001X+2016_T1,dff9476c7f05f26a69a06506fe471668,problem_get,556186425e7448e189918bafcb2ff30b,2016-04-01T21:04:38,0
29165537,466786,2659552,course-v1:TsinghuaX+AP000001X+2016_T1,dff9476c7f05f26a69a06506fe471668,problem_get,1757e4fd85994ba9a2350780f96da89e,2016-04-01T21:04:38,0
29165538,466786,2659552,course-v1:TsinghuaX+AP000001X+2016_T1,dff9476c7f05f26a69a06506fe471668,problem_get,686d5efcd27845379b4b90e41ece181d,2016-04-01T21:04:38,0
29165539,466786,2659552,course-v1:TsinghuaX+AP000001X+2016_T1,d94bf93252b8936bef09f6e46c24d50d,click_about,NaN,2016-03-02T20:21:55,0

In [9]:
left.to_csv('./data_process/row_train.csv',index = 0)

In [8]:
#将测试集中的log和truth进行合并
df3 = pd.read_csv('./row_data/test_log.csv')
df4 = pd.read_csv('./row_data/test_truth.csv')
right = pd.merge(df3,df4,on=['enroll_id'],how='left')
right

,enroll_id,username,course_id,session_id,action,object,time,truth
0,775,1520977,course-v1:TsinghuaX+70800232X+2015_T2,5f421f644193c2d48c84df42aaf7e48b,load_video,3dac5590435e43b3a65a9ae7426c16db,2015-10-15T22:14:11,1
1,775,1520977,course-v1:TsinghuaX+70800232X+2015_T2,5f421f644193c2d48c84df42aaf7e48b,load_video,3169d758ee2d4262b07f0113df743c42,2015-10-15T22:43:35,1
2,775,1520977,course-v1:TsinghuaX+70800232X+2015_T2,5f421f644193c2d48c84df42aaf7e48b,play_video,3169d758ee2d4262b07f0113df743c42,2015-10-15T22:43:40,1
3,775,1520977,course-v1:TsinghuaX+70800232X+2015_T2,5f421f644193c2d48c84df42aaf7e48b,pause_video,3169d758ee2d4262b07f0113df743c42,2015-10-15T22:55:38,1
4,775,1520977,course-v1:TsinghuaX+70800232X+2015_T2,5f421f644193c2d48c84df42aaf7e48b,stop_video,3169d758ee2d4262b07f0113df743c42,2015-10-15T22:55:38,1
...,...,...,...,...,...,...,...,...
12944857,466785,2513464,course-v1:TsinghuaX+AP000001X+2016_T1,b12bc83e13cd943cf61bf78f09c72158,problem_check_incorrect,31aa97345c46473badab334379f995d8,2016-03-19T21:37:15,1
12944858,466785,2513464,course-v1:TsinghuaX+AP000001X+2016_T1,b12bc83e13cd943cf61bf78f09c72158,problem_check_incorrect,31aa97345c46473badab334379f995d8,2016-03-19T21:37:22,1
12944859,466785,2513464,course-v1:TsinghuaX+AP000001X+2016_T1,b12bc83e13cd943cf61bf78f09c72158,problem_check_correct,31aa97345c46473badab334379f995d8,2016-03-19T21:37:37,1
12944860,466785,2513464,course-v1:TsinghuaX+AP000001X+2016_T1,7eca0904ae14dc8af809c0362632dd8e,click_courseware,NaN,2016-03-19T19:24:44,1
12944861,466785,2513464,course-v1:TsinghuaX+AP000001X+2016_T1,b12bc83e13cd943cf61bf78f09c72158,problem_get,a028651adbdc4bc0b53191117f874fbc,2016-03-19T21:38:34,1

In [10]:
right.to_csv('./data_process/row_test.csv',index = 0)

In [13]:
#获得train数据的feature
train_data = pd.read_csv('./data_process/row_train.csv')

#set是对元素进行去重并按照从小到大进行排序，list是将其转化为列表形式
data_enroll = list(set(list(train_data['enroll_id'])))

video_action = ['seek_video','play_video','pause_video','stop_video','load_video']
problem_action = ['problem_get','problem_check','problem_save','reset_problem','problem_check_correct', 'problem_check_incorrect']
forum_action = ['click_forum','create_thread','create_comment','delete_thread','delete_comment','close_forum']
courseware_action = ['click_courseware','close_courseware']

#根据enroll_id统计该学生活动的总次数，并命名该列为all#count
all_num = train_data.groupby('enroll_id').count()[['action']]
all_num.columns = ['all#count']

#对每个活动进行遍历并统计次数
for a in video_action + problem_action + forum_action + courseware_action:
    action_ = (train_data['action'] == a).astype(int)
    train_data[a+'#num'] = action_
    action_num = train_data.groupby('enroll_id').sum()[[a+'#num']]
    all_num = pd.merge(all_num, action_num, left_index=True, right_index=True)

enroll_info = train_data[['username','course_id','enroll_id','truth']].drop_duplicates()

enroll_info.index = enroll_info['enroll_id']
del enroll_info['enroll_id']

all_num = pd.merge(all_num, enroll_info, left_index=True, right_index=True)

# all_num['complete'] = all_num['truth'].map(lambda x: 1 if x == 0 else 0)
# del all_num['truth']

all_num.loc[data_enroll].to_csv('./data_process/train_feature.csv')

In [15]:
#获得test数据的feature
test_data = pd.read_csv('./data_process/row_test.csv')

#set是对元素进行去重并按照从小到大进行排序，list是将其转化为列表形式
data_enroll = list(set(list(test_data['enroll_id'])))

video_action = ['seek_video','play_video','pause_video','stop_video','load_video']
problem_action = ['problem_get','problem_check','problem_save','reset_problem','problem_check_correct', 'problem_check_incorrect']
forum_action = ['click_forum','create_thread','create_comment','delete_thread','delete_comment','close_forum']
courseware_action = ['click_courseware','close_courseware']

#根据enroll_id统计该学生活动的总次数，并命名该列为all#count
all_num = test_data.groupby('enroll_id').count()[['action']]
all_num.columns = ['all#count']

#对每个活动进行遍历并统计次数
for a in video_action + problem_action + forum_action + courseware_action:
    action_ = (test_data['action'] == a).astype(int)
    test_data[a+'#num'] = action_
    action_num = test_data.groupby('enroll_id').sum()[[a+'#num']]
    all_num = pd.merge(all_num, action_num, left_index=True, right_index=True)

enroll_info = test_data[['username','course_id','enroll_id','truth']].drop_duplicates()

enroll_info.index = enroll_info['enroll_id']
del enroll_info['enroll_id']

all_num = pd.merge(all_num, enroll_info, left_index=True, right_index=True)

# all_num['complete'] = all_num['truth'].map(lambda x: 1 if x == 0 else 0)
# del all_num['truth']

all_num.loc[data_enroll].to_csv('./data_process/test_feature.csv')

In [17]:
#合并train和test，为后面的将课程数字化做铺垫
train = pd.read_csv('./data_process/train_feature.csv')
test = pd.read_csv('./data_process/test_feature.csv')
all_feature = pd.concat([train,test])
all_feature

,enroll_id,all#count,seek_video#num,play_video#num,pause_video#num,stop_video#num,load_video#num,problem_get#num,problem_check#num,problem_save#num,...,create_thread#num,create_comment#num,delete_thread#num,delete_comment#num,close_forum#num,click_courseware#num,close_courseware#num,username,course_id,truth
0,772,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,5981,course-v1:TsinghuaX+70800232X+2015_T2,1
1,773,21,6,4,3,0,1,0,0,0,...,0,0,0,0,0,2,1,1544995,course-v1:TsinghuaX+70800232X+2015_T2,1
2,774,74,9,14,10,1,8,0,0,0,...,0,0,0,0,0,17,9,1072798,course-v1:TsinghuaX+70800232X+2015_T2,1
3,776,19,0,3,3,1,2,0,0,0,...,0,0,0,0,0,4,2,561867,course-v1:TsinghuaX+70800232X+2015_T2,0
4,777,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1368125,course-v1:TsinghuaX+70800232X+2015_T2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67694,393203,4,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,29394,course-v1:UC_BerkeleyX+ColWri2_1x_2015_T1+2016_TS,1
67695,393204,4,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,3238122,course-v1:UC_BerkeleyX+ColWri2_1x_2015_T1+2016_TS,1
67696,131061,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1103805,course-v1:TsinghuaX+20220053X_2015_T2+2015_T2,1
67697,131065,6,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,79648,course-v1:TsinghuaX+20220053X_2015_T2+2015_T2,1
67698,393214,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2957641,course-v1:UC_BerkeleyX+ColWri2_1x_2015_T1+2016_TS,1

In [20]:
all_feature.to_csv('./data_process/all_features.csv',index='enroll_id')